-- MySQL Script generated by MySQL Workbench
-- Sat Jan 22 23:38:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema moodtracker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema moodtracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moodtracker` DEFAULT CHARACTER SET utf8 ;
USE `moodtracker` ;

-- -----------------------------------------------------
-- Table `moodtracker`.`mood`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moodtracker`.`mood` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moodtracker`.`occurance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moodtracker`.`occurance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `mood_id` INT NOT NULL,
  `happened_at` DATETIME NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_occurance_mood_idx` (`mood_id` ASC) VISIBLE,
  CONSTRAINT `fk_occurance_mood`
    FOREIGN KEY (`mood_id`)
    REFERENCES `moodtracker`.`mood` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `moodtracker`.`mood`
-- -----------------------------------------------------
START TRANSACTION;
USE `moodtracker`;
INSERT INTO `moodtracker`.`mood` (`id`, `name`) VALUES (DEFAULT, 'Happy');
INSERT INTO `moodtracker`.`mood` (`id`, `name`) VALUES (DEFAULT, 'Sad');
INSERT INTO `moodtracker`.`mood` (`id`, `name`) VALUES (DEFAULT, 'Angry');
INSERT INTO `moodtracker`.`mood` (`id`, `name`) VALUES (DEFAULT, 'Indifferent');
INSERT INTO `moodtracker`.`mood` (`id`, `name`) VALUES (DEFAULT, 'Unsatisfied');
INSERT INTO `moodtracker`.`mood` (`id`, `name`) VALUES (DEFAULT, 'Excited');
INSERT INTO `moodtracker`.`mood` (`id`, `name`) VALUES (DEFAULT, 'Remorseful');

COMMIT;


-- -----------------------------------------------------
-- Data for table `moodtracker`.`occurance`
-- -----------------------------------------------------
START TRANSACTION;
USE `moodtracker`;
INSERT INTO `moodtracker`.`occurance` (`id`, `created_at`, `mood_id`, `happened_at`, `description`) VALUES (DEFAULT, '2022-01-22 22:45:25', 1, '2022-01-22 22:45:25', 'I was just feeling good.');

COMMIT;

