-- MySQL Script generated by MySQL Workbench
-- Tue Jan 25 00:52:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema moodtracker
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `moodtracker` ;

-- -----------------------------------------------------
-- Schema moodtracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moodtracker` DEFAULT CHARACTER SET utf8 ;
USE `moodtracker` ;

-- -----------------------------------------------------
-- Table `moodtracker`.`mood`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moodtracker`.`mood` (
  `id` DATE NOT NULL,
  `value` INT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moodtracker`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moodtracker`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(512) NOT NULL,
  `enabled` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `moodtracker`.`mood`
-- -----------------------------------------------------
START TRANSACTION;
USE `moodtracker`;
INSERT INTO `moodtracker`.`mood` (`id`, `value`, `description`) VALUES ('2022-01-01', 4, 'It\'s new years!');

COMMIT;


-- -----------------------------------------------------
-- Data for table `moodtracker`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `moodtracker`;
INSERT INTO `moodtracker`.`user` (`id`, `name`, `password`, `enabled`) VALUES (DEFAULT, 'test_name', 'test_password', 1);

COMMIT;

